fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v0.7.1
    hooks:
      - id: add-trailing-comma
  - repo: local
    hooks:
      - id: pyformat
        name: pyformat
        entry: pyformat
        language: python
        types: [python]
        args: ["-i"]
        require_serial: false
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
      - id: reorder-python-imports
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.11.1
    hooks:
      - id: pyupgrade
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.660
    hooks:
      - id: mypy
        language_version: python3
